export const EXAMPLE_REPORTS = [
  {
    id: 'app-crash-ips',
    label: 'App crash .ips',
    sourceLabel: 'Example: App crash .ips',
    type: 'ips',
    path: './examples/app-crash.ips',
  },
  {
    id: 'legacy-crash',
    label: 'Legacy .crash',
    sourceLabel: 'Example: Legacy .crash',
    type: 'crash',
    path: './examples/legacy.crash',
  },
  {
    id: 'watchdog-ips',
    label: 'Watchdog .ips',
    sourceLabel: 'Example: Watchdog .ips',
    type: 'ips-watchdog-stackshot',
    path: './examples/watchdog.ips',
  },
  {
    id: 'jetsam-event',
    label: 'JetsamEvent .ips',
    sourceLabel: 'Example: JetsamEvent',
    type: 'jetsam',
    path: './examples/jetsam-event.ips',
  },
  {
    id: 'panic-full',
    label: 'panic-full .ips',
    sourceLabel: 'Example: panic-full',
    type: 'panic',
    path: './examples/panic-full.ips',
  },
  {
    id: 'analytics-text',
    label: 'Analytics .txt',
    sourceLabel: 'Example: Analytics text',
    type: 'analytics',
    path: './examples/analytics.txt',
  },
  {
    id: 'coreanalytics',
    label: 'CoreAnalytics',
    sourceLabel: 'Example: CoreAnalytics',
    type: 'coreanalytics',
    path: './examples/coreanalytics.ips.ca.synced',
  },
  {
    id: 'accessory-crash',
    label: 'Accessory Crash',
    sourceLabel: 'Example: Accessory Crash',
    type: 'accessory-crash',
    path: './examples/accessory-crash.ips',
  },
  {
    id: 'cpu-resource',
    label: 'CPU Resource',
    sourceLabel: 'Example: CPU Resource',
    type: 'resource-cpu',
    path: './examples/cpu-resource.ips',
  },
  {
    id: 'disk-writes-resource',
    label: 'Disk Writes Resource',
    sourceLabel: 'Example: Disk Writes Resource',
    type: 'resource-diskwrites',
    path: './examples/disk-writes-resource.ips',
  },
  {
    id: 'stackshot-resource',
    label: 'Stackshot Resource',
    sourceLabel: 'Example: Stackshot Resource',
    type: 'resource-stackshot',
    path: './examples/stackshot-resource.ips',
  },
];
